# https://www.netlify.com/docs/netlify-toml-reference/
[build]
publish = "public"
command = "hugo --gc --minify -b $URL"

[build.environment]
NODE_VERSION = "16"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_GOOGLEANALYTICS = "dev"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
