name: Nightly build
on:
  schedule:
    - cron: "13 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deployment
        run: curl -s -X POST "${BUILD_HOOK}"
        env:
          BUILD_HOOK: ${{ secrets.VERCEL_BUILD_HOOK }}
